site_name: Techie
nav:
    - Home: checklist.md
    - Python:
        - 'function': 'CS61A/ex-function.md'
        - 'recursion': 'CS61A/ex-recursion.md'
        - 'sequence': 'CS61A/ex-sequence.md'
        - 'tree': 'CS61A/ex-tree.md'
        - 'linked_list': 'CS61A/ex-linked_list.md'
        - 'CS61A-intro': 'CS61A/1-intro.md'
        - 'CS61A-function': 'CS61A/2-function.md'
        - 'CS61A-data abstraction': 'CS61A/3-data_abstraction.md'
        - 'CS61A-object oriented': 'CS61A/4-object_oriented.md'
    - DevOps:
        - 'git': 'devops/git.md'
    - Apache:
        - 'Hadoop': 'Apache/Hadoop.md'
        - 'MapReduce': 'Apache/MapReduce.md'
        - 'HDFS': 'Apache/HDFS.md'
        - 'Spark': 'Apache/Spark.md'
theme:
    name: mkdocs